version: '3'

services:
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3001:3000
    user: '104'
    depends_on:
      - postgres
    networks:
      - planka-network
    volumes:
      - ./data:/data
      - "./grafana.ini:/etc/grafana/grafana.ini"
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource

  planka:
    image: ghcr.io/plankanban/planka:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - 3000:1337
    environment:
      - BASE_URL=http://localhost:3000
      - TRUST_PROXY=0
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=notsecretkey
    depends_on:
      - postgres
    networks:
      - planka-network

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - planka-network

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:

networks:
  planka-network:
